services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - backend
      - keycloak
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs