services:
  postgres:
    image: 'postgres:latest'
    container_name: db
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=p'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'
    volumes:
      - ~/volumes/postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
