services:
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0.1
    command:
      - start-dev
      - --import-realm
    ports:
      - 8081:8080
    volumes:
      - ./realm/:/opt/keycloak/data/import/
    env_file: .env
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    cap_drop: [ALL]
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live',
    #     ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 20
